---
# tasks file for /usr/local/google/home/friasc/apigee-workspace/apigee-opdk-role-workspace/apigee-opdk-modules
- block:
  - name: Find yml property files
    find:
      path: '{{ item }}'
      pattern: '*.yml'
      file_type: file
      hidden: yes
      recurse: yes
    with_items: "{{ property_folders }}"
    register: props

  - name: Load variables
    include_vars:
      file: "{{ item.1.path | expanduser }}"
    with_subelements:
    - "{{ props.results }}"
    - files

  delegate_to: localhost
  when: property_folders is defined
