---
# tasks file for /usr/local/google/home/friasc/apigee-workspace/apigee-opdk-role-workspace/apigee-opdk-modules
- name: Find yml property files
  find:
    path: '{{ item }}'
    pattern: '*.yml'
    file_type: file
    hidden: yes
    recurse: no
  with_items: "{{ property_folders }}"
  register: props
  when: property_folders is defined and property_folders | trim | length > 0
  delegate_to: localhost

- name: Load variables
  include_vars:
    file: "{{ item.1.path | expanduser }}"
  with_subelements:
  - "{{ props.results }}"
  - files
  when: props is defined and props.results is defined
  delegate_to: localhost
